// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using absa.phonebook.api.Data;

namespace absa.phonebook.api.Migrations
{
    [DbContext(typeof(PhonebookContext))]
    partial class PhonebookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("absa.phonebook.api.Data.Models.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<Guid>("PhonebookId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhonebookId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25f097a4-ac24-40f7-9af5-150173cddfa9"),
                            Name = "Mom",
                            Number = "081-704-6758",
                            PhonebookId = new Guid("dca21998-eeab-4291-aae2-44a7b5e8ff03")
                        },
                        new
                        {
                            Id = new Guid("02ec8615-8a3a-4dae-a1a5-7ffdbf2312df"),
                            Name = "Dad",
                            Number = "081-365-8532",
                            PhonebookId = new Guid("dca21998-eeab-4291-aae2-44a7b5e8ff03")
                        },
                        new
                        {
                            Id = new Guid("6d19c635-0530-4868-a69b-5d40617057ad"),
                            Name = "Mr D",
                            Number = "011-342-1720",
                            PhonebookId = new Guid("dca21998-eeab-4291-aae2-44a7b5e8ff03")
                        });
                });

            modelBuilder.Entity("absa.phonebook.api.Data.Models.Phonebook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Phonebooks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dca21998-eeab-4291-aae2-44a7b5e8ff03"),
                            Name = "General"
                        });
                });

            modelBuilder.Entity("absa.phonebook.api.Data.Models.Entry", b =>
                {
                    b.HasOne("absa.phonebook.api.Data.Models.Phonebook", "Phonebook")
                        .WithMany("Entries")
                        .HasForeignKey("PhonebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phonebook");
                });

            modelBuilder.Entity("absa.phonebook.api.Data.Models.Phonebook", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
