// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using absa.phonebook.api.Data;

namespace absa.phonebook.api.Migrations
{
    [DbContext(typeof(PhonebookContext))]
    partial class PhonebookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("absa.phonebook.api.Data.Models.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<Guid?>("PhonebookId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhonebookId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("absa.phonebook.api.Data.Models.Phonebook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Phonebooks");
                });

            modelBuilder.Entity("absa.phonebook.api.Data.Models.Entry", b =>
                {
                    b.HasOne("absa.phonebook.api.Data.Models.Phonebook", "Phonebook")
                        .WithMany()
                        .HasForeignKey("PhonebookId");

                    b.Navigation("Phonebook");
                });
#pragma warning restore 612, 618
        }
    }
}
